# Question 3

In [ ]:
import scipy.io.wavfile as wavfile
import scipy
import numpy as np
import matplotlib.pyplot as plt
import librosa
from scipy.signal import resample

## Part 1 

OPENNING FILES

In [ ]:
clean1_file_name = "/content/drive/MyDrive/Singal HW Practical/clean1.wav"
distorted1_file_name = "/content/drive/MyDrive/Singal HW Practical/distorted1.wav"
distorted2_file_name = "/content/drive/MyDrive/Singal HW Practical/distorted2.wav"

clean1_sample_rate, clean1_signal = wavfile.read(clean1_file_name)
distorted1_sample_rate, distorted1_signal = wavfile.read(distorted1_file_name)
distorted2_sample_rate, distorted2_signal = wavfile.read(distorted2_file_name)
main_size1 = distorted1_signal.shape[0]
main_size2 = distorted2_signal.shape[0]

# resampling to make sample rate same for both signals
sample_rate = min(clean1_sample_rate, distorted1_sample_rate, distorted2_sample_rate)
# clean1_sample_rate, distorted1_sample_rate, distorted2_sample_rate = sample_rate, sample_rate, sample_rate
# clean1_signal = resample(clean1_signal, sample_rate)
# distorted1_signal = resample(distorted1_signal, sample_rate)
distorted2_signal = resample(distorted2_signal, distorted1_signal.shape[0])
print((clean1_sample_rate, distorted1_sample_rate, distorted2_sample_rate))
sample_rate, "#\n", clean1_signal, clean1_signal.shape, "#\n", distorted1_signal, distorted1_signal.shape, "#\n", distorted2_signal, distorted2_signal.shape

(8000, 8000, 8000)


(8000,
 '#\n',
 array([41, 61, 12, ...,  8, 12, 12], dtype=int16),
 (16998,),
 '#\n',
 array([ 5, 11,  7, ..., 27, 27, 25], dtype=int16),
 (16998,),
 '#\n',
 array([-0.04600399, -0.04435594,  0.0355661 , ...,  7.31647873,
        -1.54493807, -4.28563437]),
 (16998,))

PLAYING SOUNDS

In [ ]:
# ! pip install IPython
import IPython

In [ ]:
IPython.display.Audio(clean1_file_name)

In [ ]:
IPython.display.Audio(distorted1_file_name)

In [ ]:
IPython.display.Audio(distorted2_file_name)

CONVERTING TO FREQUENCY DOMAIN AND CALCULATING FREQUENCY RESPOSNE

$ DistortedInFrequencyDomain = FrequencyRespose.CleanInFrequencyDomain$ 

In [ ]:
clean1_fft = scipy.fft.fft(clean1_signal)
clean1_freq = scipy.fft.fftfreq(len(clean1_fft), (1.0/sample_rate)) 

distorted1_fft = scipy.fft.fft(distorted1_signal)
distorted1_freq = scipy.fft.fftfreq(len(distorted1_fft), (1.0/sample_rate)) 


frequency_response = distorted1_fft/clean1_fft
frequency_response_freq = scipy.fft.fftfreq(len(frequency_response), (1.0/sample_rate)) 

CLEANNING DISTORTED 2

As i was testing this part, it seems that distorted 2 is wrongly clean and with multiplying with frequency_response we get a distorted sound.
So maybe question was provided with wrong data.

In [ ]:
print(distorted2_signal, distorted2_signal.shape)
distorted2_fft = scipy.fft.fft(distorted2_signal)
distorted2_freq = scipy.fft.fftfreq(len(distorted2_fft), (1.0/sample_rate)) 

clean2_fft = distorted2_fft/frequency_response
clean2_freq = scipy.fft.fftfreq(len(clean2_fft), (1.0/sample_rate))
print(distorted2_fft[0], frequency_response[0], clean2_fft[0])

[-0.04600399 -0.04435594  0.0355661  ...  7.31647873 -1.54493807
 -4.28563437] (16998,)
(-8124.387408989529-0j) (1.042929851737114-0j) (-7789.965351415986-0j)


CONVERTING TO TIME DOMAIN AND SAVE WAV FILE

In [ ]:
clean2_ifft = scipy.fft.ifft(clean2_fft)
clean2_ifft = resample(clean2_ifft, main_size2)

print(clean2_ifft, clean2_ifft.shape)
clean2_file_name = "/content/drive/MyDrive/Singal HW Practical/recovered2.wav"

wavfile.write(clean2_file_name, sample_rate, clean2_ifft.astype(clean1_signal.dtype))

[  5389.51228561-4.55853855e-11j  23095.10628708-1.10652085e-10j
  18321.23806188+3.62984590e-13j ...  -5850.5243707 -9.36739948e-12j
 -13046.33011416-7.45008749e-11j -14623.78429063-1.11793261e-11j] (22937,)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: ComplexWarning: Casting complex values to real discards the imaginary part
  import sys


PLAYING CLEAN 2



In [ ]:
IPython.display.Audio(clean2_file_name)

Methodology is clear, first we calculate frequency response of system in frequency domain then with that, we can predict system output in frequency domain with every given input. After that, we can convert response in frequency domain to time domain.